/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function buildInsertRecord(filepath: string, urlPath: string, content: string): void
export function buildCommit(): void
export function search(text: string): Array<Record>
export class Record {
  filepath: string
  urlPath: string
  content: string
}
