/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Record {
  fileLocation: string
  urlPath: string
  content: string
}
export class SearchIndex {
  constructor()
  clear(): void
  insert(records: Array<Record>): void
  search(text: string): Array<Record>
}
